version: "3.8"

services:
  hop-server:
    image: apache/hop:latest
    container_name: joli_hop_server
    hostname: hop-server
    ports:
      - "5678:8080"
    environment:
      - HOP_OPTIONS=-Xmx2048m
      - HOP_PROJECT=JoliDataHub
      - HOP_PROJECT_FOLDER=/files/project
    entrypoint: /bin/bash
    command: >
      -c "echo '--- Generando Configuración de Seguridad ---';
      /opt/hop/hop-conf.sh -s -sn JoliServer -sh 0.0.0.0 -sp 8080 -su admin_joli -spwd 8Dtv6wEvGoNwBafRb;
      echo '--- Registrando Proyectos ---';
      /opt/hop/hop-conf.sh -pc -p JoliDataHub -ph /files/project;
      /opt/hop/hop-conf.sh -pc -p project1 -ph /files/project;
      echo '--- Iniciando Servidor Blindado ---';
      /opt/hop/hop-server.sh /root/.config/hop/config/hop-server.xml"
    volumes:
      - ./project:/files/project
      - ./drivers:/opt/hop/lib/jdbc
    restart: unless-stopped

  hop-web:
    image: apache/hop-web:latest
    container_name: hop-web-pro
    user: root
    expose:
      - "8080"
    environment:
      - HOP_OPTIONS=-Xmx2g
      - HOP_PROJECT_NAME=JoliDataHub
      - HOP_PROJECT_FOLDER=/files/project
    volumes:
      - ./project:/files/project
      - ./drivers:/opt/hop/lib/jdbc
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "8088:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd:ro
    depends_on:
      - hop-web
    restart: unless-stopped